#! /bin/bash

XP=002

echo "COMMAND	: $0 take pictures"
echo "XP	: Experiment XP$XP"

IMAGES=/var/firefuse/calibration
GCODEFIRE=/dev/firefuse/sync/cnc/marlin/gcode.fire
if [ ! -e $GCODEFIRE ]; then
  echo "ERROR	: FireFUSE serial connection to Marlin is unavailable"
  echo "TRY	: See /var/log/firefuse.log for details"
  exit -1
fi

function gcode() {
  if [ "$2" != "" ]; then echo "STATUS	: $2"; fi
  echo "GCODE	: $1"
  echo "$1" > $GCODEFIRE
  RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit -1; fi
  return $RC
}

function imageAt() {
  sleep 1
  gcode G0$1M400
  sleep 1
  cp /dev/firefuse/sync/cv/1/camera.jpg /dev/null

  for IMG in `seq 1 1 3`
  do
	  FILE=$IMAGES/XP$XP_$1#${IMG}@$2.jpg
	  echo "IMAGE	: $FILE"
	  cp /dev/firefuse/sync/cv/1/camera.jpg $FILE 
	  RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit -1; fi
  done
}

echo "STATUS	: taking images for calibrating pixels per mm"
gcode G28Z0M400 "Homing"
sleep 3
gcode G0Z0Y0Z0M400 "Moving to origin"
sleep 5

echo "STATUS	: removing prior experiment results"
rm /var/firefuse/calibration/XP$XP*.jpg

for REP in `seq 1 1 3`
do
	for Z in `seq -0.0 -0.5 -4.0`
	do
		gcode G0Z0Y0Z10M400 "Moving out of vision plane"
		imageAt Z${Z}X10Y10 $REP
	done
done

