#!/bin/bash

XP=002

if [ -e /var/firefuse/calibration/XP002-A1.1_X10Y10Z0.jpg ]; then
  IMAGES=/var/firefuse/calibration
else
  IMAGES=img
fi

for FILE in `ls $IMAGES/XP$XP*`
do
	JSON=`firesight -p ../json/matchGrid.json -Dtemplate=../img/cross32.png -i $FILE `
	echo $FILE `echo $JSON | grep -o -E 'gridY":[-0-9. ]*'`
done
