#! /bin/bash

XP=001

echo "COMMAND	: $0 take pictures"
echo "XP	: Experiment $XP"

IMAGES=/var/firefuse/calibration
GCODEFIRE=/dev/firefuse/sync/cnc/marlin/gcode.fire
if [ ! -e $GCODEFIRE ]; then
  echo "ERROR	: FireFUSE serial connection to Marlin is unavailable"
  echo "TRY	: See /var/log/firefuse.log for details"
  exit -1
fi

function gcode() {
  if [ "$2" != "" ]; then echo "STATUS	: $2"; fi
  echo "GCODE	: $1"
  echo "$1" > $GCODEFIRE
  RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit -1; fi
  return $RC
}

function imageAt() {
  FILE=$IMAGES/$XP-$1-$2.jpg
  echo "IMAGE	: $FILE"
  sleep 1
  gcode G0$1
  sleep 1
  cp /dev/firefuse/sync/cv/1/camera.jpg $FILE // ignore first image
  cp /dev/firefuse/sync/cv/1/camera.jpg $FILE 
  RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit -1; fi
}

echo "STATUS	: taking images for calibrating pixels per mm"
gcode G28Z0M400 "Homing"
sleep 3
gcode G0Z0Y0Z0M400 "Moving to origin"
sleep 5

for i in `seq 1 1 5`
do
	gcode G0Z0Y0Z10 "Moving out of vision plane"
	imageAt X10Y10Z0 $i
	gcode G0Z0Y0Z10 "Moving out of vision plane"
	imageAt X10Y10Z0.1 $i
done

