#! /bin/bash

IMAGES=/var/firefuse/calibration
GCODEFIRE=/dev/firefuse/sync/cnc/marlin/gcode.fire
if [ ! -e $GCODEFIRE ]; then
  echo "ERROR	: FireFUSE serial connection to Marlin is unavailable"
  echo "TRY	: See /var/log/firefuse.log for details"
  exit -1
fi

function gcode() {
  if [ "$2" != "" ]; then echo "STATUS	: $2"; fi
  echo "GCODE	: $1"
  echo "$1" > $GCODEFIRE
  RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit -1; fi
  return $RC
}

function imageAt() {
  echo "IMAGE	: $1"
  gcode G0$1M400
  RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: echo $GCODE > $GCODEFIRE => $RC"; exit -1; fi
  cp /dev/firefuse/sync/cv/1/camera.jpg $IMAGES/$1.jpg
  RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit -1; fi
}

echo "STATUS	: taking images for calibrating pixels per mm"
gcode G28Z0M400 "Homing"
sleep 3
gcode G0Z0Y0Z0M400 "Moving to origin"
sleep 5

for i in `seq 1 1 3`
do
	sleep 1
	imageAt X10Y10Z0
	imageAt X10Y10Z0
	mv /var/firefuse/calibration/X10Y10Z0.jpg /var/firefuse/calibration/X10Y10Z0-$i.jpg
	gcode G0Z0Y0Z10M400 "Moving out of vision plane"
	sleep 1
	imageAt X10Y10Z0.1
	imageAt X10Y10Z0.1
	mv /var/firefuse/calibration/X10Y10Z0.1.jpg /var/firefuse/calibration/X10Y10Z0.1-$i.jpg
done

